const pinkLine = [
    "Majlis Park",
    "Azadpur",
    "Shalimar Bagh",
    "Netaji Subhash Place",
    "Shakurpur",
    "Punjabi Bagh West",
    "ESI Basaidarapur",
    "Rajouri Garden",
    "Maya Puri",
    "Nariana Vihar",
    "Delhi Cantt",
    "Durgabai Deshmukh South Campus",
    "Sir Vishweshwaraiah Moti Bagh",
    "Bhikaji Cama Place",
    "Sarojini Nagar",
    "Dilli Hat INA",
    "South Extension",
    "Lajpat Nagar",
    "Vinobapuri",
    "Ashram",
    "Sarai Kale Khan Hazrat Nizamuddin",
    "Mayur Vihar - I",
    "Mayur Vihar Pocket 1",
    "Trilok Puri Sanjay Lake",
    "East Mandawali West Vinod Nagar Mayur Vihar II",
    "Mandawali West Vinod Nagar",
    "IP Extension",
    "Anand Vihar",
    "Karkarduma",
    "Karkarduma Court",
    "Krishna Nagar",
    "East Azad Nagar",
    "Welcome",
    "Jaffrabad",
    "Maujpur",
    "Gokul Puri",
    "Johri Enclave",
    "Shiv Vihar",
  ];
  
  const redLine = [
    "Shaheed Sthal (New Bus Adda)",
    "Hindon",
    "Arthala",
    "Mohan Nagar",
    "Shyam park",
    "Major Mohit Sharma",
    "Raj Bagh",
    "Shaheed Nagar",
    "Dilshad Garden",
    "Jhilmil",
    "Mansarovar Park",
    "Shahdara",
    "Welcome",
    "Seelampur",
    "Shastri Park",
    "Kashmere Gate",
    "Tis Hazari",
    "Pul Bangash",
    "Pratap Nagar",
    "Shastri Nagar",
    "Inderlok",
    "Kanhiya Nagar",
    "Keshav Puram",
    "Netaji Subhash Place",
    "Kohat Enclave",
    "Pitam Pura",
    "Rohini East",
    "Rohini West",
    "Rithala",
  ];
  
  const blueLine1 = [
    "Noida Electronic City",
    "Noida Sector 62",
    "Noida Sector 59",
    "Noida Sector 61",
    "Noida Sector 52",
    "Noida Sector 34",
    "Noida City Centre",
    "Golf Course",
    "Botanical Garden",
    "Noida Sector 18",
    "Noida Sector 16",
    "Noida Sector 15",
    "New Ashok Nagar",
    "Mayur Vihar Extension",
    "Mayur Vihar I",
    "Akshardham",
    "Yamuna Bank",
    "Indraprastha",
    "Pragati Maidan",
    "Mandi House",
    "Barakhamba Road",
    "Rajiv Chowk",
    "Ramakrishna Ashram Marg",
    "Jhandewalan",
    "Karol Bagh",
    "Rajendra Place",
    "Patel Nagar",
    "Shadipur",
    "Kirti Nagar",
    "Moti Nagar",
    "Ramesh Nagar",
    "Rajouri Garden",
    "Tagore Garden",
    "Subhash Nagar",
    "Tilak Nagar",
    "Janakpuri East",
    "Janakpuri West",
    "Uttam Nagar East",
    "Uttam Nagar West",
    "Nawada",
    "Dwarka Mor",
    "Dwarka",
    "Dwarka Sector 14",
    "Dwarka Sector 13",
    "Dwarka Sector 12",
    "Dwarka Sector 11",
    "Dwarka Sector 10",
    "Dwarka Sector 9",
    "Dwarka Sector 8",
    "Dwarka Sector 21",
  ];
  
  const blueLine2 = [
    "Yamuna Bank",
    "Laxmi Nagar",
    "Nirman Vihar",
    "Preet Vihar",
    "Karkarduma",
    "Anand Vihar",
    "Kaushambi",
    "Vaishali",
  ];
  
  const yellowLine = [
    "Samaypur Badli",
    "Rohini Sector 18, 19",
    "Haiderpur Badli Mor",
    "Jahangirpuri",
    "Adarsh Nagar",
    "Azadpur",
    "Model Town",
    "GTB Nagar",
    "Vishwa Vidyalaya",
    "Vidhan Sabha",
    "Civil Lines",
    "Kashmere Gate",
    "Chandni Chowk",
    "Chawri Bazar",
    "New Delhi",
    "Rajiv Chowk",
    "Patel Chowk",
    "Central Secretariat",
    "Udyog Bhawan",
    "Lok Kalyan Marg",
    "Jor Bagh",
    "Dilli Hat INA",
    "AIIMS",
    "Green Park",
    "Hauz Khas",
    "Malviya Nagar",
    "Saket",
    "Qutub Minar",
    "Chhatarpur",
    "Sultanpur",
    "Ghitorni",
    "Arjan Garh",
    "Guru Dronacharya",
    "Sikandarpur",
    "MG Road",
    "IFFCO Chowk",
    "Huda City Centre",
  ];
  
  const greenLine = [
    "Kirti Nagar",
    "Satguru Ram Singh Marg",
    "Inderlok",
    "Ashok Park Main",
    "Punjabi Bagh",
    "Shivaji Park",
    "Madipur",
    "Paschim Vihar East",
    "Paschim Vihar West",
    "Peera Garhi",
    "Udyog Nagar",
    "Surajmal Stadium",
    "Nangloi",
    "Nangloi Railway Station",
    "Rajdhani Park",
    "Mundka",
    "Mundka Industrial Area",
    "Ghevra",
    "Tikri Kalan",
    "Tikri Border",
    "Pandit Shree Ram Sharma",
    "Bahadurgarh City",
    "Brigadier Hoshiyar Singh",
  ];
  
  const voiletLine = [
    "Kashmere Gate",
    "Lal Qila",
    "Jama Masjid",
    "Delhi Gate",
    "ITO",
    "Mandi House",
    "Janpath",
    "Central Secretariat",
    "Khan Market",
    "Jawaharlal Nehru Stadium",
    "Jangpura",
    "Lajpat Nagar",
    "Moolchand",
    "Kailash Colony",
    "Nehru Place",
    "Kalkaji Mandir",
    "Govind Puri",
    "Harkesh Nagar",
    "Jasola Apollo",
    "Sarita Vihar",
    "Mohan Estate",
    "Tughlakabad",
    "Badarpur",
    "Sarai",
    "NHPC Chowk",
    "Mewla Maharajpur",
    "Sector 28",
    "Badkhal Mor",
    "Faridabad Old",
    "Neelam Chowk Ajronda",
    "Bata Chowk",
    "Escorts Mujesar",
    "Sant Surdas — Sihi (NCB Colony)",
    "Raja Nahar Singh (Ballabhgarh)",
  ];
  
  const magentaLine = [
    "Janakpuri West",
    "Dabri Mor Janakpuri South",
    "Dashrath Puri",
    "Palam",
    "Sadar Bazaar Cantonment",
    "Terminal 1 Indira Gandhi Airport",
    "Shankar Vihar",
    "Vasant Vihar",
    "Munirka",
    "RK Puram",
    "IIT Delhi",
    "Hauz Khas",
    "Panchsheel Park",
    "Chirag Delhi",
    "Greater Kailash",
    "Nehru Enclave",
    "Kalkaji Mandir",
    "Okhla NSIC",
    "Sukhdev Vihar",
    "Jamia Millia Islamia",
    "Okhla Vihar",
    "Jasola Vihar Shaheen Bagh",
    "Kalindi Kunj",
    "Okhla Bird Sanctuary",
    "Botanical Garden",
  ];
  
  const airportExpressLines = [
    "Yashobhoomi Dwarka Sector 25",
    "Dwarka Sector 21",
    "Indira Gandhi Airport",
    "Delhi Aerocity",
    "Dhaula Kuan",
    "Shivaji Stadium",
    "New Delhi",
  ];

const entirMetroMap30 = [
  pinkLine,
  redLine,
  blueLine1,
  blueLine2,
  yellowLine,
  greenLine,
  voiletLine,
  magentaLine,
  airportExpressLines,
];

const entirMetroStation52 = entirMetroMap30.flat(100);
function checkValidation(start, end) {
    if(!entirMetroStation52.includes(start)){
        alert("Please Enter Valid Starting Station:")
        return false;
    }
    if(!entirMetroStation52.includes(end)){
        alert("Please Enter Valid Ending Station:")
        return false;
    }
    return true
}
